In [1]:
# Import our dependencies
import os
import pandas as pd
import numpy as np

In [2]:
# Create Dataframe for war dataset
url = 'https://raw.githubusercontent.com/brianrwheatley/final-baseball-war-stats/main/Resources/jeffbagwell_war_historical.csv'
war_df = pd.read_csv(url, encoding='latin-1')
war_df.head()

,player_name,age,key_bbref,year_ID,team_ID,stint_ID,lg_ID,is_P,franch_ID,sched,...,gms_RF,gms_OF,gms_DH,gms_PH,gms_PR,prev_tm,arrived,departed,next_tm,salary
0,David Aardsma,22.0,aardsda01,2004,SFG,1,NL,Y,SFG,162,...,0.0,0.0,0.0,0.0,0.0,---,2004,2004,CHC,300000.0
1,David Aardsma,24.0,aardsda01,2006,CHC,1,NL,Y,CHC,162,...,0.0,0.0,0.0,0.0,0.0,SFG,2006,2006,CHW,NaN
2,David Aardsma,25.0,aardsda01,2007,CHW,1,AL,Y,CHW,162,...,0.0,0.0,0.0,0.0,0.0,CHC,2007,2007,BOS,387500.0
3,David Aardsma,26.0,aardsda01,2008,BOS,1,AL,Y,BOS,162,...,0.0,0.0,0.0,0.0,0.0,CHW,2008,2008,SEA,403250.0
4,David Aardsma,27.0,aardsda01,2009,SEA,1,AL,Y,SEA,162,...,0.0,0.0,0.0,0.0,0.0,BOS,2009,2010,NYY,419000.0

In [3]:
# Create seperate Dataframe for injury dataset
url2 = 'https://raw.githubusercontent.com/brianrwheatley/final-baseball-war-stats/finding_injury_length/final_injury_data.csv'
injury_df = pd.read_csv(url2, encoding='latin-1')
injury_df

,Unnamed: 0,Name,Team,Date,Status,injury_length,Injury,location,days_injured,year,shortname
0,0,Brian Johnson,Red Sox,6/15/17,Placed,10-day,shoulder impingement,left,NaN,2017,bjohnson
1,1,Brian Johnson,Red Sox,7/6/17,Activated,10-day,NaN,NaN,21.0,2017,bjohnson
2,2,Brian Johnson,Red Sox,7/8/18,Placed,10-day,hip inflammation,left,NaN,2018,bjohnson
3,3,Brian Johnson,Red Sox,7/15/18,Activated,10-day,NaN,NaN,7.0,2018,bjohnson
4,4,Brian Johnson,Red Sox,4/6/19,Placed,10-day,elbow inflammation,left,NaN,2019,bjohnson
...,...,...,...,...,...,...,...,...,...,...,...
14800,14800,Zack Wheeler,Mets,11/3/17,Activated,60-day,NaN,NaN,102.0,2017,zwheeler
14801,14801,Zack Wheeler,Mets,7/15/19,Placed,10-day,shoulder fatigue,right,NaN,2019,zwheeler
14802,14802,Zack Wheeler,Mets,7/26/19,Activated,10-day,NaN,NaN,11.0,2019,zwheeler
14803,14803,Zoilo Almonte,Yankees,7/20/13,Placed,15-day,sprained ankle,left,NaN,2013,zalmonte
14804,14804,Zoilo Almonte,Yankees,9/9/13,Activated,15-day,NaN,NaN,51.0,2013,zalmonte

In [4]:
# Filter Dataframe to years in question >=2010
war_df=war_df[war_df.year_ID >=2010]
war_df

,player_name,age,key_bbref,year_ID,team_ID,stint_ID,lg_ID,is_P,franch_ID,sched,...,gms_RF,gms_OF,gms_DH,gms_PH,gms_PR,prev_tm,arrived,departed,next_tm,salary
5,David Aardsma,28.0,aardsda01,2010,SEA,1,AL,Y,SEA,162,...,0.0,0.0,0.0,0.0,0.0,BOS,2009,2010,NYY,2750000.0
6,David Aardsma,30.0,aardsda01,2012,NYY,1,AL,Y,NYY,162,...,0.0,0.0,0.0,0.0,0.0,SEA,2012,2012,NYM,500000.0
7,David Aardsma,31.0,aardsda01,2013,NYM,1,NL,Y,NYM,162,...,0.0,0.0,0.0,0.0,0.0,NYY,2013,2013,ATL,NaN
8,David Aardsma,33.0,aardsda01,2015,ATL,1,NL,Y,ATL,162,...,0.0,0.0,0.0,0.0,0.0,NYM,2015,2015,---,NaN
55,Fernando Abad,24.0,abadfe01,2010,HOU,1,NL,Y,HOU,162,...,0.0,0.0,0.0,0.0,0.0,---,2010,2012,WSN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111976,Mike Zunino,30.0,zuninmi01,2021,TBR,1,AL,N,TBD,162,...,0.0,0.0,0.0,5.0,0.0,SEA,2019,2022,---,2000000.0
111977,Mike Zunino,31.0,zuninmi01,2022,TBR,1,AL,N,TBD,29,...,0.0,0.0,0.0,2.0,0.0,SEA,2019,2022,---,7000000.0
112009,Tony Zych,24.0,zychto01,2015,SEA,1,AL,Y,SEA,162,...,0.0,0.0,0.0,0.0,0.0,---,2015,2017,---,NaN
112010,Tony Zych,25.0,zychto01,2016,SEA,1,AL,Y,SEA,162,...,0.0,0.0,0.0,0.0,0.0,---,2015,2017,---,511000.0
112011,Tony Zych,26.0,zychto01,2017,SEA,1,AL,Y,SEA,162,...,0.0,0.0,0.0,0.0,0.0,---,2015,2017,---,539600.0

In [5]:
# Combine same year and player in Injury_df
new_injury_df = injury_df.groupby(["Name", "year"]).agg({"Team": "first", "Name": "first", "Team" : "first","injury_length": "first", "Injury": "first", "location": "first", "days_injured" : "first", "year": "first", "shortname": "first"} )
new_injury_df.reset_index(drop=True, inplace=True)
#injury_df.groupby(["Name", "year"])
new_injury_df.to_csv("clean_injury.csv")
new_injury_df

,Team,Name,injury_length,Injury,location,days_injured,year,shortname
0,Pirates,A.J. Burnett,15-day,fractured orbital bone,right,17.0,2012,aburnett
1,Pirates,A.J. Burnett,15-day,strained calf,right,24.0,2013,aburnett
2,Pirates,A.J. Burnett,15-day,elbow inflammation,right,41.0,2015,aburnett
3,Yankees,A.J. Cole,10-day,strained neck,left,12.0,2018,acole
4,Indians,A.J. Cole,10-day,shoulder impingement,right,86.0,2019,acole
...,...,...,...,...,...,...,...,...
6101,Mets,Zack Wheeler,15-day,None,None,212.0,2015,zwheeler
6102,Mets,Zack Wheeler,15-day,None,None,214.0,2016,zwheeler
6103,Mets,Zack Wheeler,10-day,biceps tendinitis,right,10.0,2017,zwheeler
6104,Mets,Zack Wheeler,10-day,shoulder fatigue,right,11.0,2019,zwheeler
6105,Yankees,Zoilo Almonte,15-day,sprained ankle,left,51.0,2013,zalmonte

In [6]:
# Merge of dataframes to test in machine learning.  
injury_war_df = pd.merge(war_df, new_injury_df, how = 'left', left_on= ['player_name', 'year_ID'], right_on= ["Name", "year"])
injury_war_df

,player_name,age,key_bbref,year_ID,team_ID,stint_ID,lg_ID,is_P,franch_ID,sched,...,next_tm,salary,Team,Name,injury_length,Injury,location,days_injured,year,shortname
0,David Aardsma,28.0,aardsda01,2010,SEA,1,AL,Y,SEA,162,...,NYY,2750000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,David Aardsma,30.0,aardsda01,2012,NYY,1,AL,Y,NYY,162,...,NYM,500000.0,Yankees,David Aardsma,60-day,NaN,NaN,211.0,2012.0,daardsma
2,David Aardsma,31.0,aardsda01,2013,NYM,1,NL,Y,NYM,162,...,ATL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,David Aardsma,33.0,aardsda01,2015,ATL,1,NL,Y,ATL,162,...,---,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fernando Abad,24.0,abadfe01,2010,HOU,1,NL,Y,HOU,162,...,WSN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18661,Mike Zunino,30.0,zuninmi01,2021,TBR,1,AL,N,TBD,162,...,---,2000000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18662,Mike Zunino,31.0,zuninmi01,2022,TBR,1,AL,N,TBD,29,...,---,7000000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18663,Tony Zych,24.0,zychto01,2015,SEA,1,AL,Y,SEA,162,...,---,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18664,Tony Zych,25.0,zychto01,2016,SEA,1,AL,Y,SEA,162,...,---,511000.0,Mariners,Tony Zych,15-day,rotator cuff tendinitis in shoulder,right,112.0,2016.0,tzych
18665,Tony Zych,26.0,zychto01,2017,SEA,1,AL,Y,SEA,162,...,---,539600.0,Mariners,Tony Zych,10-day,recovering from surgery on biceps,right,14.0,2017.0,tzych

In [7]:
# Sort the dataset by names first, then by date
injury_war_df = injury_war_df.sort_values(by = ['player_name', 'year_ID'], ascending = [True, True], na_position = 'first')
injury_war_df.head(20)

,player_name,age,key_bbref,year_ID,team_ID,stint_ID,lg_ID,is_P,franch_ID,sched,...,next_tm,salary,Team,Name,injury_length,Injury,location,days_injured,year,shortname
54,A.J. Achter,25.0,achteaj01,2014,MIN,1,AL,Y,MIN,162,...,ANA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,A.J. Achter,26.0,achteaj01,2015,MIN,1,AL,Y,MIN,162,...,ANA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,A.J. Achter,27.0,achteaj01,2016,LAA,1,AL,Y,ANA,162,...,---,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,A.J. Alexy,23.0,alexyaj01,2021,TEX,1,AL,Y,TEX,162,...,---,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2232,A.J. Burnett,33.0,burnea.01,2010,NYY,1,AL,Y,NYY,162,...,PIT,16500000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2233,A.J. Burnett,34.0,burnea.01,2011,NYY,1,AL,Y,NYY,162,...,PIT,16500000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2234,A.J. Burnett,35.0,burnea.01,2012,PIT,1,NL,Y,PIT,162,...,PHI,16500000.0,Pirates,A.J. Burnett,15-day,fractured orbital bone,right,17.0,2012.0,aburnett
2235,A.J. Burnett,36.0,burnea.01,2013,PIT,1,NL,Y,PIT,162,...,PHI,16500000.0,Pirates,A.J. Burnett,15-day,strained calf,right,24.0,2013.0,aburnett
2236,A.J. Burnett,37.0,burnea.01,2014,PHI,1,NL,Y,PHI,162,...,PIT,15000000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2237,A.J. Burnett,38.0,burnea.01,2015,PIT,1,NL,Y,PIT,162,...,---,8500000.0,Pirates,A.J. Burnett,15-day,elbow inflammation,right,41.0,2015.0,aburnett
3316,A.J. Cole,23.0,coleaj01,2015,WSN,1,NL,Y,WSN,162,...,NYY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3317,A.J. Cole,24.0,coleaj01,2016,WSN,1,NL,Y,WSN,162,...,NYY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3318,A.J. Cole,25.0,coleaj01,2017,WSN,1,NL,Y,WSN,162,...,NYY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3319,A.J. Cole,26.0,coleaj01,2018,WSN,1,NL,Y,WSN,162,...,NYY,555300.0,Yankees,A.J. Cole,10-day,strained neck,left,12.0,2018.0,acole
3320,A.J. Cole,26.0,coleaj01,2018,NYY,2,AL,Y,NYY,162,...,CLE,NaN,Yankees,A.J. Cole,10-day,strained neck,left,12.0,2018.0,acole
3321,A.J. Cole,27.0,coleaj01,2019,CLE,1,AL,Y,CLE,162,...,TOR,NaN,Indians,A.J. Cole,10-day,shoulder impingement,right,86.0,2019.0,acole
3322,A.J. Cole,28.0,coleaj01,2020,TOR,1,AL,Y,TOR,60,...,---,100000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3323,A.J. Cole,29.0,coleaj01,2021,TOR,1,AL,Y,TOR,162,...,---,1000000.0,Blue Jays,A.J. Cole,10-day,tightness in neck,None,96.0,2021.0,acole
4813,A.J. Ellis,29.0,ellisaj01,2010,LAD,1,NL,N,LAD,162,...,PHI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4814,A.J. Ellis,30.0,ellisaj01,2011,LAD,1,NL,N,LAD,161,...,PHI,421000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
injury_war_df.columns

Index(['player_name', 'age', 'key_bbref', 'year_ID', 'team_ID', 'stint_ID',
       'lg_ID', 'is_P', 'franch_ID', 'sched', 'g_bat', 'pa', 'bat162',
       'bsr162', 'fld162', 'pos162', 'def162', 'rep162', 'bwar162', 'BB_plus',
       'K_plus', 'AVG_plus', 'OBP_plus', 'SLG_plus', 'wRC_plus', 'ISO_plus',
       'BABIP_plus', 'LD_plus', 'GB_plus', 'FB_plus', 'Pull_plus', 'Cent_plus',
       'Oppo_plus', 'g_pitch', 'starts', 'innings', 'relief_pct', 'avg_LI',
       'br_pwar162', 'fg_pwar162', 'ra9_pwar162', 'pwar162', 'K9_plus',
       'BB9_plus', 'KBB_plus', 'HR9_plus', 'Kpct_plus', 'BBpct_plus',
       'oppAVG_plus', 'WHIP_plus', 'oppBABIP_plus', 'LOB_plus', 'ERA_minus',
       'FIP_minus', 'xFIP_minus', 'oppLD_plus', 'oppGB_plus', 'oppFB_plus',
       'pct_PT', 'WAR162', 'gms_P', 'gms_C', 'gms_1B', 'gms_2B', 'gms_3B',
       'gms_SS', 'gms_LF', 'gms_CF', 'gms_RF', 'gms_OF', 'gms_DH', 'gms_PH',
       'gms_PR', 'prev_tm', 'arrived', 'departed', 'next_tm', 'salary', 'Team',
       'Name', 'injury_length', 'Injury', 'location', 'days_injured', 'year',
       'shortname'],
      dtype='object')

In [9]:
injury_war_df['WAR_change'] = ''
injury_war_df['WAR_difference'] = ''
injury_war_df

,player_name,age,key_bbref,year_ID,team_ID,stint_ID,lg_ID,is_P,franch_ID,sched,...,Team,Name,injury_length,Injury,location,days_injured,year,shortname,WAR_change,WAR_difference
54,A.J. Achter,25.0,achteaj01,2014,MIN,1,AL,Y,MIN,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,
55,A.J. Achter,26.0,achteaj01,2015,MIN,1,AL,Y,MIN,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,
56,A.J. Achter,27.0,achteaj01,2016,LAA,1,AL,Y,ANA,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,
262,A.J. Alexy,23.0,alexyaj01,2021,TEX,1,AL,Y,TEX,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,
2232,A.J. Burnett,33.0,burnea.01,2010,NYY,1,AL,Y,NYY,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16067,Zeke Spruill,23.0,spruize01,2013,ARI,1,NL,Y,ARI,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,
16068,Zeke Spruill,24.0,spruize01,2014,ARI,1,NL,Y,ARI,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,
18010,Zelous Wheeler,27.0,wheelze01,2014,NYY,1,AL,N,NYY,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,
333,Zoilo Almonte,24.0,almonzo01,2013,NYY,1,AL,N,NYY,162,...,Yankees,Zoilo Almonte,15-day,sprained ankle,left,51.0,2013.0,zalmonte,,
334,Zoilo Almonte,25.0,almonzo01,2014,NYY,1,AL,N,NYY,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,

In [10]:
player_list = injury_war_df['player_name'].tolist()
war162_list = injury_war_df['WAR162'].tolist()
new_list = [player_list, war162_list]
new_list

[['A.J. Achter',
  'A.J. Achter',
  'A.J. Achter',
  'A.J. Alexy',
  'A.J. Burnett',
  'A.J. Burnett',
  'A.J. Burnett',
  'A.J. Burnett',
  'A.J. Burnett',
  'A.J. Burnett',
  'A.J. Cole',
  'A.J. Cole',
  'A.J. Cole',
  'A.J. Cole',
  'A.J. Cole',
  'A.J. Cole',
  'A.J. Cole',
  'A.J. Cole',
  'A.J. Ellis',
  'A.J. Ellis',
  'A.J. Ellis',
  'A.J. Ellis',
  'A.J. Ellis',
  'A.J. Ellis',
  'A.J. Ellis',
  'A.J. Ellis',
  'A.J. Ellis',
  'A.J. Ellis',
  'A.J. Griffin',
  'A.J. Griffin',
  'A.J. Griffin',
  'A.J. Griffin',
  'A.J. Jimenez',
  'A.J. Minter',
  'A.J. Minter',
  'A.J. Minter',
  'A.J. Minter',
  'A.J. Minter',
  'A.J. Minter',
  'A.J. Morris',
  'A.J. Pierzynski',
  'A.J. Pierzynski',
  'A.J. Pierzynski',
  'A.J. Pierzynski',
  'A.J. Pierzynski',
  'A.J. Pierzynski',
  'A.J. Pierzynski',
  'A.J. Pierzynski',
  'A.J. Puk',
  'A.J. Puk',
  'A.J. Puk',
  'A.J. Schugel',
  'A.J. Schugel',
  'A.J. Schugel',
  'AJ Pollock',
  'AJ Pollock',
  'AJ Pollock',
  'AJ Pollock',
  'AJ Pollock',
  'AJ Pollock',
  'AJ Pollock',
  'AJ Pollock',
  'AJ Pollock',
  'AJ Pollock',
  'AJ Pollock',
  'AJ Ramos',
  'AJ Ramos',
  'AJ Ramos',
  'AJ Ramos',
  'AJ Ramos',
  'AJ Ramos',
  'AJ Ramos',
  'AJ Ramos',
  'AJ Ramos',
  'AJ Ramos',
  'AJ Reed',
  'AJ Reed',
  'AJ Reed',
  'AJ Reed',
  'Aaron Altherr',
  'Aaron Altherr',
  'Aaron Altherr',
  'Aaron Altherr',
  'Aaron Altherr',
  'Aaron Altherr',
  'Aaron Altherr',
  'Aaron Altherr',
  'Aaron Ashby',
  'Aaron Ashby',
  'Aaron Barrett',
  'Aaron Barrett',
  'Aaron Barrett',
  'Aaron Barrett',
  'Aaron Blair',
  'Aaron Blair',
  'Aaron Brooks',
  'Aaron Brooks',
  'Aaron Brooks',
  'Aaron Brooks',
  'Aaron Brooks',
  'Aaron Brooks',
  'Aaron Brooks',
  'Aaron Bummer',
  'Aaron Bummer',
  'Aaron Bummer',
  'Aaron Bummer',
  'Aaron Bummer',
  'Aaron Bummer',
  'Aaron Civale',
  'Aaron Civale',
  'Aaron Civale',
  'Aaron Civale',
  'Aaron Cook',
  'Aaron Cook',
  'Aaron Cook',
  'Aaron Crow',
  'Aaron Crow',
  'Aaron Crow',
  'Aaron Crow',
  'Aaron Cunningham',
  'Aaron Cunningham',
  'Aaron Cunningham',
  'Aaron Fletcher',
  'Aaron Fletcher',
  'Aaron Fletcher',
  'Aaron Harang',
  'Aaron Harang',
  'Aaron Harang',
  'Aaron Harang',
  'Aaron Harang',
  'Aaron Harang',
  'Aaron Harang',
  'Aaron Heilman',
  'Aaron Heilman',
  'Aaron Hicks',
  'Aaron Hicks',
  'Aaron Hicks',
  'Aaron Hicks',
  'Aaron Hicks',
  'Aaron Hicks',
  'Aaron Hicks',
  'Aaron Hicks',
  'Aaron Hicks',
  'Aaron Hicks',
  'Aaron Hill',
  'Aaron Hill',
  'Aaron Hill',
  'Aaron Hill',
  'Aaron Hill',
  'Aaron Hill',
  'Aaron Hill',
  'Aaron Hill',
  'Aaron Hill',
  'Aaron Hill',
  'Aaron Judge',
  'Aaron Judge',
  'Aaron Judge',
  'Aaron Judge',
  'Aaron Judge',
  'Aaron Judge',
  'Aaron Judge',
  'Aaron Laffey',
  'Aaron Laffey',
  'Aaron Laffey',
  'Aaron Laffey',
  'Aaron Laffey',
  'Aaron Laffey',
  'Aaron Laffey',
  'Aaron Loup',
  'Aaron Loup',
  'Aaron Loup',
  'Aaron Loup',
  'Aaron Loup',
  'Aaron Loup',
  'Aaron Loup',
  'Aaron Loup',
  'Aaron Loup',
  'Aaron Loup',
  'Aaron Loup',
  'Aaron Loup',
  'Aaron Miles',
  'Aaron Miles',
  'Aaron Nola',
  'Aaron Nola',
  'Aaron Nola',
  'Aaron Nola',
  'Aaron Nola',
  'Aaron Nola',
  'Aaron Nola',
  'Aaron Nola',
  'Aaron Northcraft',
  'Aaron Poreda',
  'Aaron Rowand',
  'Aaron Rowand',
  'Aaron Sanchez',
  'Aaron Sanchez',
  'Aaron Sanchez',
  'Aaron Sanchez',
  'Aaron Sanchez',
  'Aaron Sanchez',
  'Aaron Sanchez',
  'Aaron Sanchez',
  'Aaron Sanchez',
  'Aaron Slegers',
  'Aaron Slegers',
  'Aaron Slegers',
  'Aaron Slegers',
  'Aaron Slegers',
  'Aaron Thompson',
  'Aaron Thompson',
  'Aaron Thompson',
  'Aaron Whitefield',
  'Aaron Wilkerson',
  'Aaron Wilkerson',
  'Aaron Wilkerson',
  'Abel De Los Santos',
  'Abel De Los Santos',
  'Abiatal Avelino',
  'Abiatal Avelino',
  'Abraham Almonte',
  'Abraham Almonte',
  'Abraham Almonte',
  'Abraham Almonte',
  'Abraham Almonte',
  'Abraham Almonte',
  'Abraham Almonte',
  'Abraham Almonte',
  'Abraham Almonte',
  'Abraham Almonte',
  'Abraham Almonte',
  'Abraham Toro',
  'Abraham Toro',
  'Abraham Toro',
  'Abraham Toro',
  'Abraham Toro',
  'Adalberto Mejia',
  'Adalberto Mejia',
  'Adalberto Mejia',
  'Adalberto Mejia',
  'Adalberto Mejia',
  'Adalberto Mejia',
  'Adalberto Mendez',
  'Adalberto MondesÃ­',
  'Adalberto MondesÃ­',
  'Adalberto MondesÃ­',
  'Adalberto MondesÃ­',
  'Adalberto MondesÃ­',
  'Adalberto MondesÃ­',
  'Adalberto MondesÃ­',
  'Adam Cimber',
  'Adam Cimber',
  'Adam Cimber',
  'Adam Cimber',
  'Adam Cimber',
  'Adam Cimber',
  'Adam Cimber',
  'Adam Conley',
  'Adam Conley',
  'Adam Conley',
  'Adam Conley',
  'Adam Conley',
  'Adam Conley',
  'Adam Dunn',
  'Adam Dunn',
  'Adam Dunn',
  'Adam Dunn',
  'Adam Dunn',
  'Adam Dunn',
  'Adam Duvall',
  'Adam Duvall',
  'Adam Duvall',
  'Adam Duvall',
  'Adam Duvall',
  'Adam Duvall',
  'Adam Duvall',
  'Adam Duvall',
  'Adam Duvall',
  'Adam Duvall',
  'Adam Duvall',
  'Adam Eaton',
  'Adam Eaton',
  'Adam Eaton',
  'Adam Eaton',
  'Adam Eaton',
  'Adam Eaton',
  'Adam Eaton',
  'Adam Eaton',
  'Adam Eaton',
  'Adam Eaton',
  'Adam Eaton',
  'Adam Engel',
  'Adam Engel',
  'Adam Engel',
  'Adam Engel',
  'Adam Engel',
  'Adam Engel',
  'Adam Everett',
  'Adam Everett',
  'Adam Frazier',
  'Adam Frazier',
  'Adam Frazier',
  'Adam Frazier',
  'Adam Frazier',
  'Adam Frazier',
  'Adam Frazier',
  'Adam Frazier',
  'Adam Greenberg',
  'Adam Haseley',
  'Adam Haseley',
  'Adam Haseley',
  'Adam Haseley',
  'Adam Jones',
  'Adam Jones',
  'Adam Jones',
  'Adam Jones',
  'Adam Jones',
  'Adam Jones',
  'Adam Jones',
  'Adam Jones',
  'Adam Jones',
  'Adam Jones',
  'Adam Kennedy',
  'Adam Kennedy',
  'Adam Kennedy',
  'Adam Kolarek',
  'Adam Kolarek',
  'Adam Kolarek',
  'Adam Kolarek',
  'Adam Kolarek',
  'Adam Kolarek',
  'Adam Kolarek',
  'Adam LaRoche',
  'Adam LaRoche',
  'Adam LaRoche',
  'Adam LaRoche',
  'Adam LaRoche',
  'Adam LaRoche',
  'Adam Liberatore',
  'Adam Liberatore',
  'Adam Liberatore',
  'Adam Liberatore',
  'Adam Lind',
  'Adam Lind',
  'Adam Lind',
  'Adam Lind',
  'Adam Lind',
  'Adam Lind',
  'Adam Lind',
  'Adam Lind',
  'Adam Loewen',
  'Adam Loewen',
  'Adam Loewen',
  'Adam McCreery',
  'Adam Moore',
  'Adam Moore',
  'Adam Moore',
  'Adam Moore',
  'Adam Moore',
  'Adam Moore',
  'Adam Moore',
  'Adam Moore',
  'Adam Morgan',
  'Adam Morgan',
  'Adam Morgan',
  'Adam Morgan',
  'Adam Morgan',
  'Adam Morgan',
  'Adam Morgan',
  'Adam Oller',
  'Adam Ottavino',
  'Adam Ottavino',
  'Adam Ottavino',
  'Adam Ottavino',
  'Adam Ottavino',
  'Adam Ottavino',
  'Adam Ottavino',
  'Adam Ottavino',
  'Adam Ottavino',
  'Adam Ottavino',
  'Adam Ottavino',
  'Adam Ottavino',
  'Adam Plutko',
  'Adam Plutko',
  'Adam Plutko',
  'Adam Plutko',
  'Adam Plutko',
  'Adam Rosales',
  'Adam Rosales',
  'Adam Rosales',
  'Adam Rosales',
  'Adam Rosales',
  'Adam Rosales',
  'Adam Rosales',
  'Adam Rosales',
  'Adam Rosales',
  'Adam Rosales',
  'Adam Rosales',
  'Adam Russell',
  'Adam Russell',
  'Adam Stern',
  'Adam Wainwright',
  'Adam Wainwright',
  'Adam Wainwright',
  'Adam Wainwright',
  'Adam Wainwright',
  'Adam Wainwright',
  'Adam Wainwright',
  'Adam Wainwright',
  'Adam Wainwright',
  'Adam Wainwright',
  'Adam Wainwright',
  'Adam Wainwright',
  'Adam Warren',
  'Adam Warren',
  'Adam Warren',
  'Adam Warren',
  'Adam Warren',
  'Adam Warren',
  'Adam Warren',
  'Adam Warren',
  'Adam Warren',
  'Adam Warren',
  'Adam Wilk',
  'Adam Wilk',
  'Adam Wilk',
  'Adam Wilk',
  'Adam Wilk',
  'Adbert Alzolay',
  'Adbert Alzolay',
  'Adbert Alzolay',
  'Addison Reed',
  'Addison Reed',
  'Addison Reed',
  'Addison Reed',
  'Addison Reed',
  'Addison Reed',
  'Addison Reed',
  'Addison Reed',
  'Addison Reed',
  'Addison Reed',
  'Addison Russell',
  'Addison Russell',
  'Addison Russell',
  'Addison Russell',
  'Addison Russell',
  'Adeiny Hechavarria',
  'Adeiny Hechavarria',
  'Adeiny Hechavarria',
  'Adeiny Hechavarria',
  'Adeiny Hechavarria',
  'Adeiny Hechavarria',
  'Adeiny Hechavarria',
  'Adeiny Hechavarria',
  'Adeiny Hechavarria',
  'Adeiny Hechavarria',
  'Adeiny Hechavarria',
  'Adeiny Hechavarria',
  'Adeiny Hechavarria',
  'Adolis GarcÃ­a',
  'Adolis GarcÃ­a',
  'Adolis GarcÃ­a',
  'Adolis GarcÃ­a',
  'Adonis Garcia',
  'Adonis Garcia',
  'Adonis Garcia',
  'Adonis Medina',
  'Adonis Medina',
  'Adonis Medina',
  'Adonis Rosa',
  'Adrian Beltre',
  'Adrian Beltre',
  'Adrian Beltre',
  'Adrian Beltre',
  'Adrian Beltre',
  'Adrian Beltre',
  'Adrian Beltre',
  'Adrian Beltre',
  'Adrian Beltre',
  'Adrian Cardenas',
  'Adrian Gonzalez',
  'Adrian Gonzalez',
  'Adrian Gonzalez',
  'Adrian Gonzalez',
  'Adrian Gonzalez',
  'Adrian Gonzalez',
  'Adrian Gonzalez',
  'Adrian Gonzalez',
  'Adrian Gonzalez',
  'Adrian Gonzalez',
  'Adrian Houser',
  'Adrian Houser',
  'Adrian Houser',
  'Adrian Houser',
  'Adrian Houser',
  'Adrian Houser',
  'Adrian Nieto',
  'Adrian Sampson',
  'Adrian Sampson',
  'Adrian Sampson',
  'Adrian Sampson',
  'Adrian Sampson',
  'Adrian Sanchez',
  'Adrian Sanchez',
  'Adrian Sanchez',
  'Adrian Sanchez',
  'AdriÃ¡n MorejÃ³n',
  'AdriÃ¡n MorejÃ³n',
  'AdriÃ¡n MorejÃ³n',
  'Adron Chambers',
  'Adron Chambers',
  'Adron Chambers',
  'Akeel Morris',
  'Akeel Morris',
  'Akeel Morris',
  'Akeem Bostick',
  'Akil Baddoo',
  'Akil Baddoo',
  'Akinori Iwamura',
  'Akinori Iwamura',
  'Al Alburquerque',
  'Al Alburquerque',
  'Al Alburquerque',
  'Al Alburquerque',
  'Al Alburquerque',
  'Al Alburquerque',
  'Al Alburquerque',
  'Al Alburquerque',
  'Alan Busenitz',
  'Alan Busenitz',
  'Alan Johnson',
  'Alan Trejo',
  'Alan Trejo',
  'Albert Abreu',
  'Albert Abreu',
  'Albert Abreu',
  'Albert Almora',
  'Albert Almora',
  'Albert Almora',
  'Albert Almora',
  'Albert Almora',
  'Albert Almora',
  'Albert Almora',
  'Albert Pujols',
  'Albert Pujols',
  'Albert Pujols',
  'Albert Pujols',
  'Albert Pujols',
  'Albert Pujols',
  'Albert Pujols',
  'Albert Pujols',
  'Albert Pujols',
  'Albert Pujols',
  'Albert Pujols',
  'Albert Pujols',
  'Albert Pujols',
  'Albert Pujols',
  'Albert Suarez',
  'Albert Suarez',
  'Alberto Baldonado',
  'Alberto Cabrera',
  'Alberto Cabrera',
  'Alberto Callaspo',
  'Alberto Callaspo',
  'Alberto Callaspo',
  'Alberto Callaspo',
  'Alberto Callaspo',
  'Alberto Callaspo',
  'Alberto Callaspo',
  'Alberto Callaspo',
  'Alberto Callaspo',
  'Alberto Castillo',
  'Alberto Castillo',
  'Alberto Gonzalez',
  'Alberto Gonzalez',
  'Alberto Gonzalez',
  'Alberto Gonzalez',
  'Alberto Gonzalez',
  'Alberto Rosario',
  'Alberto Rosario',
  'Alcides Escobar',
  'Alcides Escobar',
  'Alcides Escobar',
  'Alcides Escobar',
  'Alcides Escobar',
  'Alcides Escobar',
  'Alcides Escobar',
  'Alcides Escobar',
  'Alcides Escobar',
  'Alcides Escobar',
  'Alcides Escobar',
  'Alec Asher',
  'Alec Asher',
  'Alec Asher',
  'Alec Asher',
  'Alec Bettinger',
  'Alec Bohm',
  'Alec Bohm',
  'Alec Bohm',
  'Alec Mills',
  'Alec Mills',
  'Alec Mills',
  'Alec Mills',
  'Alec Mills',
  'Aledmys DÃ­az',
  'Aledmys DÃ­az',
  'Aledmys DÃ­az',
  'Aledmys DÃ­az',
  'Aledmys DÃ­az',
  'Aledmys DÃ­az',
  'Aledmys DÃ­az',
  'Alejandro Chacin',
  'Alejandro De Aza',
  'Alejandro De Aza',
  'Alejandro De Aza',
  'Alejandro De Aza',
  'Alejandro De Aza',
  'Alejandro De Aza',
  'Alejandro De Aza',
  'Alejandro De Aza',
  'Alejandro De Aza',
  'Alejandro De Aza',
  'Alejandro De Aza',
  'Alejandro Kirk',
  'Alejandro Kirk',
  'Alejandro Kirk',
  'Alejo Lopez',
  'Alejo Lopez',
  'Alek Manoah',
  'Alek Manoah',
  'Alek Thomas',
  'Alen Hanson',
  'Alen Hanson',
  'Alen Hanson',
  'Alen Hanson',
  'Alen Hanson',
  'Alex Avila',
  'Alex Avila',
  'Alex Avila',
  'Alex Avila',
  'Alex Avila',
  'Alex Avila',
  'Alex Avila',
  'Alex Avila',
  'Alex Avila',
  'Alex Avila',
  'Alex Avila',
  'Alex Avila',
  'Alex Avila',
  'Alex Blandino',
  'Alex Blandino',
  'Alex Blandino',
  'Alex Bregman',
  'Alex Bregman',
  'Alex Bregman',
  'Alex Bregman',
  'Alex Bregman',
  'Alex Bregman',
  'Alex Bregman',
  'Alex Burnett',
  'Alex Burnett',
  'Alex Burnett',
  'Alex Burnett',
  'Alex Burnett',
  'Alex Castellanos',
  'Alex Castellanos',
  'Alex Claudio',
  'Alex Claudio',
  'Alex Claudio',
  'Alex Claudio',
  'Alex Claudio',
  'Alex Claudio',
  'Alex Claudio',
  'Alex Claudio',
  'Alex Cobb',
  'Alex Cobb',
  'Alex Cobb',
  'Alex Cobb',
  'Alex Cobb',
  'Alex Cobb',
  'Alex Cobb',
  'Alex Cobb',
  'Alex Cobb',
  'Alex Cobb',
  'Alex Cobb',
  'Alex Colome',
  'Alex Colome',
  'Alex Colome',
  'Alex Colome',
  'Alex Colome',
  'Alex Colome',
  'Alex Colome',
  'Alex Colome',
  'Alex Colome',
  'Alex Colome',
  'Alex Colome',
  'Alex Cora',
  'Alex Cora',
  'Alex Cora',
  'Alex De Goti',
  'Alex Dickerson',
  'Alex Dickerson',
  'Alex Dickerson',
  'Alex Dickerson',
  'Alex Dickerson',
  'Alex Dickerson',
  'Alex Dickerson',
  'Alex Faedo',
  'Alex Gonzalez',
  'Alex Gonzalez',
  'Alex Gonzalez',
  'Alex Gonzalez',
  'Alex Gonzalez',
  'Alex Gonzalez',
  'Alex Gordon',
  'Alex Gordon',
  'Alex Gordon',
  'Alex Gordon',
  'Alex Gordon',
  'Alex Gordon',
  'Alex Gordon',
  'Alex Gordon',
  'Alex Gordon',
  'Alex Gordon',
  'Alex Gordon',
  'Alex Guerrero',
  'Alex Guerrero',
  'Alex Hassan',
  'Alex Hinshaw',
  'Alex Hinshaw',
  'Alex Jackson',
  'Alex Jackson',
  'Alex Jackson',
  'Alex Jackson',
  'Alex Jackson',
  'Alex Kirilloff',
  'Alex Kirilloff',
  'Alex Lange',
  'Alex Lange',
  'Alex Liddi',
  'Alex Liddi',
  'Alex Liddi',
  'Alex McRae',
  'Alex McRae',
  'Alex McRae',
  'Alex McRae',
  'Alex Mejia',
  'Alex Meyer',
  'Alex Meyer',
  'Alex Meyer',
  'Alex Meyer',
  'Alex Presley',
  'Alex Presley',
  'Alex Presley',
  'Alex Presley',
  'Alex Presley',
  'Alex Presley',
  'Alex Presley',
  'Alex Presley',
  'Alex Presley',
  'Alex Presley',
  'Alex Reyes',
  'Alex Reyes',
  'Alex Reyes',
  'Alex Reyes',
  'Alex Reyes',
  'Alex Rios',
  'Alex Rios',
  'Alex Rios',
  'Alex Rios',
  'Alex Rios',
  'Alex Rios',
  'Alex Rios',
  'Alex Rodriguez',
  'Alex Rodriguez',
  'Alex Rodriguez',
  'Alex Rodriguez',
  'Alex Rodriguez',
  'Alex Rodriguez',
  'Alex Sanabia',
  'Alex Sanabia',
  'Alex Sanabia',
  'Alex Torres',
  'Alex Torres',
  'Alex Torres',
  'Alex Torres',
  'Alex Verdugo',
  'Alex Verdugo',
  'Alex Verdugo',
  'Alex Verdugo',
  'Alex Verdugo',
  'Alex Verdugo',
  'Alex Vesia',
  'Alex Vesia',
  'Alex Vesia',
  'Alex White',
  'Alex White',
  'Alex White',
  'Alex Wilson',
  'Alex Wilson',
  'Alex Wilson',
  'Alex Wilson',
  'Alex Wilson',
  'Alex Wilson',
  'Alex Wilson',
  'Alex Wimmers',
  'Alex Wimmers',
  'Alex Wood',
  'Alex Wood',
  'Alex Wood',
  'Alex Wood',
  'Alex Wood',
  'Alex Wood',
  'Alex Wood',
  'Alex Wood',
  'Alex Wood',
  'Alex Wood',
  'Alex Wood',
  'Alex Young',
  'Alex Young',
  'Alex Young',
  'Alex Young',
  'Alexander Wells',
  'Alexander Wells',
  'Alexei RamÃ­rez',
  'Alexei RamÃ­rez',
  'Alexei RamÃ­rez',
  'Alexei RamÃ­rez',
  'Alexei RamÃ­rez',
  'Alexei RamÃ­rez',
  'Alexei RamÃ­rez',
  'Alexei RamÃ­rez',
  'Alexi Amarista',
  'Alexi Amarista',
  'Alexi Amarista',
  'Alexi Amarista',
  'Alexi Amarista',
  'Alexi Amarista',
  'Alexi Amarista',
  'Alexi Amarista',
  'Alexi Casilla',
  'Alexi Casilla',
  'Alexi Casilla',
  'Alexi Casilla',
  'Alexi Casilla',
  'Alexi Ogando',
  'Alexi Ogando',
  'Alexi Ogando',
  'Alexi Ogando',
  'Alexi Ogando',
  'Alexi Ogando',
  'Alexi Ogando',
  'Alexi Ogando',
  'Alexis Diaz',
  'Alfonso Rivas',
  'Alfonso Rivas',
  'Alfonso Soriano',
  'Alfonso Soriano',
  'Alfonso Soriano',
  'Alfonso Soriano',
  'Alfonso Soriano',
  'Alfonso Soriano',
  'Alfredo Aceves',
  'Alfredo Aceves',
  'Alfredo Aceves',
  'Alfredo Aceves',
  'Alfredo Aceves',
  'Alfredo Amezaga',
  'Alfredo Amezaga',
  'Alfredo Figaro',
  'Alfredo Figaro',
  'Alfredo Figaro',
  'Alfredo Gonzalez',
  'Alfredo Marte',
  'Alfredo Marte',
  'Alfredo Marte',
  'Alfredo Simon',
  'Alfredo Simon',
  'Alfredo Simon',
  'Alfredo Simon',
  'Alfredo Simon',
  'Alfredo Simon',
  'Alfredo Simon',
  'Ali Sanchez',
  'Ali Sanchez',
  'Ali Solis',
  'Ali Solis',
  'Allan Dykstra',
  'Allen Cordoba',
  'Allen Craig',
  'Allen Craig',
  'Allen Craig',
  'Allen Craig',
  'Allen Craig',
  'Allen Craig',
  'Allen Craig',
  'Allen Webster',
  'Allen Webster',
  'Allen Webster',
  'Allen Webster',
  'Allen Webster',
  'Amauri Sanit',
  'Amed Rosario',
  'Amed Rosario',
  'Amed Rosario',
  'Amed Rosario',
  'Amed Rosario',
  'Amed Rosario',
  'Amir Garrett',
  'Amir Garrett',
  'Amir Garrett',
  'Amir Garrett',
  'Amir Garrett',
  'Amir Garrett',
  'Anderson Hernandez',
  'Anderson Hernandez',
  'Anderson Severino',
  'Anderson Tejeda',
  'Anderson Tejeda',
  'Andre Ethier',
  'Andre Ethier',
  'Andre Ethier',
  'Andre Ethier',
  'Andre Ethier',
  'Andre Ethier',
  'Andre Ethier',
  'Andre Ethier',
  'Andre Jackson',
  'Andre Pallante',
  'Andre Rienzo',
  'Andre Rienzo',
  'Andre Rienzo',
  'Andre Scrubb',
  'Andre Scrubb',
  'Andrelton Simmons',
  'Andrelton Simmons',
  'Andrelton Simmons',
  'Andrelton Simmons',
  'Andrelton Simmons',
  'Andrelton Simmons',
  'Andrelton Simmons',
  'Andrelton Simmons',
  'Andrelton Simmons',
  'Andrelton Simmons',
  'Andres Blanco',
  'Andres Blanco',
  'Andres Blanco',
  'Andres Blanco',
  'Andres Blanco',
  'Andres Blanco',
  'Andres Gimenez',
  'Andres Gimenez',
  'Andres Gimenez',
  'Andres Machado',
  'Andres Machado',
  'Andres Machado',
  'Andres Munoz',
  'Andres Munoz',
  'Andres Munoz',
  'Andres Torres',
  'Andres Torres',
  'Andres Torres',
  'Andres Torres',
  'Andrew Albers',
  'Andrew Albers',
  'Andrew Albers',
  'Andrew Albers',
  'Andrew Albers',
  'Andrew Bailey',
  'Andrew Bailey',
  'Andrew Bailey',
  'Andrew Bailey',
  'Andrew Bailey',
  'Andrew Bailey',
  'Andrew Bailey',
  'Andrew Bailey',
  'Andrew Bellatti',
  'Andrew Bellatti',
  'Andrew Bellatti',
  'Andrew Benintendi',
  'Andrew Benintendi',
  'Andrew Benintendi',
  'Andrew Benintendi',
  'Andrew Benintendi',
  'Andrew Benintendi',
  'Andrew Benintendi',
  'Andrew Brackman',
  'Andrew Brown',
  'Andrew Brown',
  'Andrew Brown',
  'Andrew Brown',
  'Andrew Carignan',
  'Andrew Carignan',
  'Andrew Cashner',
  'Andrew Cashner',
  'Andrew Cashner',
  'Andrew Cashner',
  'Andrew Cashner',
  'Andrew Cashner',
  'Andrew Cashner',
  'Andrew Cashner',
  ...],
 [-0.076666667,
  -0.193333333,
  0.193333333,
  0.17,
  0.24,
  0.175,
  2.938333333,
  2.405,
  0.49,
  2.575,
  -0.235,
  -0.063333333,
  0.803333333,
  -0.37,
  -0.153333333,
  -0.003333333,
  1.575,
  0.253333333,
  -0.085,
  0.342111801,
  2.945,
  2.2,
  -0.915,
  1.16,
  -0.315,
  0.195,
  0.25,
  0.115,
  1.936666667,
  2.328333333,
  0.825,
  0.19,
  -0.225,
  0.416666667,
  1.08,
  -0.53,
  2.214,
  0.602049689,
  2.052,
  -0.098333333,
  1.055,
  1.25,
  3.28,
  1.033619632,
  -0.52,
  -0.465,
  1.15,
  -1.544534161,
  0.24,
  -0.07,
  2.487857143,
  -0.386666667,
  0.553333333,
  0.685,
  -0.05,
  2.705,
  3.145,
  6.835,
  0.34,
  2.345,
  2.245,
  0.275,
  2.295,
  3.08,
  -3.27,
  0.046666667,
  0.74,
  1.536666667,
  1.856666667,
  1.452298137,
  0.326666667,
  0.063333333,
  -0.43,
  0.045,
  0.176666667,
  -0.69,
  -0.135,
  -0.09,
  -0.51484472,
  -0.045,
  1.655,
  -0.295,
  1.76,
  -0.545,
  -0.551666667,
  0.0,
  -0.3,
  -0.015,
  -0.446896552,
  0.426666667,
  0.26,
  -0.156666667,
  -0.027,
  -1.516024845,
  -0.108333333,
  -0.47,
  0.026666667,
  -0.588333333,
  0.06,
  0.04,
  0.121666667,
  -1.234285714,
  -0.07,
  0.166666667,
  2.263975155,
  0.945,
  0.696666667,
  -1.44,
  1.705,
  1.998,
  1.846666667,
  -4.281428571,
  0.658333333,
  -0.125,
  -0.83,
  1.16,
  0.99,
  0.366666667,
  -0.513333333,
  0.35,
  0.18,
  -0.575,
  -0.459,
  -0.16,
  -1.88,
  -0.295,
  1.241666667,
  1.573333333,
  -0.455,
  0.258333333,
  2.218333333,
  0.733333333,
  -0.031666667,
  -0.828333333,
  0.535,
  0.26,
  1.715,
  -0.26,
  3.34,
  4.275,
  0.885,
  2.484,
  -0.09,
  2.7,
  1.075,
  -0.875,
  1.545,

In [11]:
war_difference_list = [0]
length = len(player_list)
for i in range(length-1):
    if player_list[i] == player_list[i+1]:
        war_difference_list.append(war162_list[i] - war162_list[i+1])
    else:
        war_difference_list.append(0)
war_difference_list

[0,
 0.116666666,
 -0.386666666,
 0,
 0,
 0.065,
 -2.7633333330000003,
 0.5333333330000003,
 1.9149999999999998,
 -2.085,
 0,
 -0.171666667,
 -0.866666666,
 1.173333333,
 -0.216666667,
 -0.15,
 -1.578333333,
 1.321666667,
 0,
 -0.427111801,
 -2.6028881989999997,
 0.7449999999999997,
 3.115,
 -2.075,
 1.4749999999999999,
 -0.51,
 -0.05499999999999999,
 0.135,
 0,
 -0.3916666659999999,
 1.5033333329999998,
 0.635,
 0,
 0,
 -0.6633333330000001,
 1.61,
 -2.7439999999999998,
 1.611950311,
 -1.449950311,
 0,
 0,
 -0.19500000000000006,
 -2.03,
 2.2463803679999996,
 1.553619632,
 -0.05499999999999999,
 -1.615,
 2.694534161,
 0,
 0.31,
 -2.5578571429999997,
 0,
 -0.94,
 -0.13166666700000007,
 0,
 -2.755,
 -0.43999999999999995,
 -3.69,
 6.495,
 -2.0050000000000003,
 0.10000000000000009,
 1.9700000000000002,
 -2.02,
 -0.7850000000000001,
 6.35,
 0,
 -0.693333333,
 -0.796666667,
 -0.32000000000000006,
 0.40436852999999995,
 1.12563147,
 0.26333333400000003,
 0.493333333,
 -0.475,
 -0.13166666700000001,
 0,
 -0.5549999999999999,
 -0.04500000000000001,
 0.42484472000000006,
 0,
 -1.7,
 1.95,
 -2.055,
 2.305,
 0.0066666669999999595,
 -0.551666667,
 0.3,
 0,
 0.431896552,
 0,
 0.166666667,
 0.416666667,
 -0.129666667,
 0,
 -1.407691512,
 0,
 -0.49666666699999995,
 0.615,
 -0.6483333330000001,
 0.019999999999999997,
 -0.081666667,
 1.355952381,
 0,
 -0.236666667,
 -2.097308488,
 1.318975155,
 0.24833333299999993,
 2.136666667,
 0,
 -0.2929999999999999,
 0.15133333299999996,
 6.128095238,
 0,
 0.783333333,
 0.705,
 0,
 0.16999999999999993,
 0.6233333329999999,
 0.8799999999999999,
 0,
 0.16999999999999998,
 0.7549999999999999,
 0,
 -0.29900000000000004,
 1.72,
 0,
 -1.536666667,
 -0.33166666599999983,
 2.028333333,
 -0.713333333,
 -1.96,
 1.4849999999999999,
 0,
 0.796666666,
 0,
 0.275,
 -1.455,
 1.975,
 -3.5999999999999996,
 -0.9350000000000005,
 3.3900000000000006,
 -1.599,
 2.574,
 -2.79,
 0,
 1.95,
 -2.42,
 -3.4800000000000004,
 3.54,
 2.1950000000000003,
 -0.6749999999999999,
 -1.6949999999999998,
 2.13,
 0.19500000000000006,
 0,
 -8.639999999999999,
 2.8599999999999994,
 0.4800000000000004,
 2.3145,
 -2.9295,
 -2.91,
 0,
 0.43166666600000003,
 -0.243333333,
 -0.05499999999999999,
 0.338333333,
 -0.093333333,
 -0.101666667,
 0,
 -0.44499999999999995,
 0.17333333299999998,
 1.073333333,
 -0.060000000000000005,
 -0.656666666,
 0.5533333330000001,
 0.043333333,
 -0.13,
 -0.797333333,
 -1.4760000000000002,
 1.7280000000000002,
 0,
 -0.553664596,
 0,
 0.44999999999999996,
 -3.51,
 -2.828333333,
 3.2316666659999997,
 -1.3783333329999996,
 2.0133333329999994,
 -0.9076190469999998,
 0,
 0,
 0,
 -0.385,
 0,
 -0.18666666599999981,
 -3.0949999999999998,
 4.488333333,
 -0.558333333,
 0.578333333,
 -0.07,
 -0.575,
 2.269,
 0,
 -0.026666667000000005,
 -0.06,
 -1.316,
 1.832666667,
 0,
 -0.198333333,
 0.25,
 0,
 0,
 0.363548057,
 -0.11021472399999999,
 0,
 0.13666666700000002,
 0,
 0.020000000000000004,
 0,
 0.045,
 -0.5149999999999999,
 0.86,
 -1.4271118010000001,
 0.593664596,
 0.518447205,
 0.8450000000000001,
 -1.35,
 1.0310000000000001,
 -0.073453416,
 0,
 1.7095000000000002,
 -1.8495000000000001,
 -0.12,
 -0.177931034,
 0,
 -1.036666667,
 0.301666667,
 1.241666666,
 -0.693333333,
 0.236666667,
 0,
 0,
 0.0,
 -2.845,
 0.050000000000000266,
 -1.4460000000000002,
 3.076,
 0.8768,
 0,
 0.718333334,
 -0.223333334,
 0.019666667,
 -0.24300000000000002,
 -0.5233333330000001,
 0.9013333330000001,
 0,
 -0.6820703939999999,
 2.552070394,
 -0.950517599,
 1.005517599,
 -1.255,
 0,
 5.64,
 -4.7299999999999995,
 1.505,
 -0.24333333299999999,
 0.578333333,
 0,
 -0.525,
 -2.75,
 0.7549999999999999,
 1.0650000000000002,
 1.6749999999999998,
 -1.295,
 -1.3059999999999998,
 0.44599999999999995,
 0.45757764,
 1.4994223599999998,
 0,
 0.72,
 -4.444999999999999,
 0.45500000000000007,
 -2.585,
 5.994999999999999,
 -0.8300000000000001,
 -0.69,
 3.34,
 -1.2650000000000001,
 0.63,
 0,
 -1.14,
 0.30453416099999997,
 -1.2340341609999999,
 0.5945,
 0.5349999999999999,
 0,
 -0.05499999999999999,
 0,
 -0.54,
 -1.3243167699999998,
 -0.29068322999999996,
 0.49049999999999994,
 -0.8555000000000001,
 2.1350000000000002,
 -0.24931034499999993,
 0,
 0,
 1.397,
 0.148,
 -0.45999999999999996,
 0,
 -0.3900000000000001,
 -1.3749999999999996,
 -0.5550000000000006,
 0.07500000000000018,
 1.2850000000000001,
 1.3849999999999998,
 0.10499999999999998,
 1.51,
 1.2,
 0,
 0.20500000000000002,
 -0.14500000000000002,
 0,
 -0.656666666,
 0.15500000000000003,
 0.016666665999999997,
 -1.669333333,
 2.291,
 -0.435714286,
 0,
 1.161677019,
 -4.056677019,
 3.2350000000000003,
 -1.6649999999999998,
 3.135,
 0,
 -0.575,
 0.5666666669999999,
 -0.072576687,
 0,
 -0.925,
 0.059999999999999984,
 -1.715,
 -0.14500000000000002,
 -0.8549999999999998,
 2.98,
 -1.065,
 0,
 0.19666666700000002,
 0.06999999999999995,
 0,
 0,
 -1.395,
 -0.035,
 -0.11,
 0.16999999999999998,
 -0.06996894399999999,
 0.100621118,
 -0.06565217400000001,
 0,
 1.008333334,
 -1.185,
 0.30500000000000005,
 0.010000000000000009,
 0.258333333,
 0.245,
 0,
 0,
 -1.205,
 -1.0533333329999999,
 0.453333333,
 0.6,
 -0.14666666699999997,
 0.62,
 -2.033087934,
 0.1764212679999999,
 2.149333333,
 -0.762666667,
 1.320666667,
 0,
 -0.115082816,
 -0.673333333,
 0.604,
 1.2343333330000001,
 0,
 2.4699999999999998,
 -1.27,
 0.5,
 -0.06,
 -0.835,
 1.143333333,
 -2.318333333,
 1.9599999999999997,
 0.53,
 -0.435,
 0,
 -0.05,
 0,
 0,
 4.048333333,
 -3.875,
 -0.15000000000000036,
 5.523333334,
 -1.7733333339999997,
 1.3133333339999997,
 1.008333333,
 -2.126666667,
 -0.680747126,
 -1.5425862070000003,
 1.124285714,
 0,
 -0.9333333340000001,
 -0.65,
 -1.2300000000000002,
 3.3733333340000002,
 -1.17,
 -0.983333334,
 0.8300000000000001,
 0.35,
 0.576666667,
 0,
 0.178333334,
 -0.276666667,
 0.255,
 -0.09499999999999997,
 0,
 -1.7126666670000001,
 0.449333333,
 0,
 -0.13,
 -0.9633333329999999,
 1.5633333329999999,
 -0.661666666,
 -0.298333334,
 -2.01,
 1.1666666669999999,
 1.02,
 0.453333333,
 0,
 -0.9849999999999999,
 1.62,
 -0.4745398770000002,
 1.819539877,
 0,
 1.35,
 -2.175,
 -1.795,
 1.800031056,
 0.6249689439999999,
 -0.44,
 0.03500000000000003,
 0.635310559,
 0.01968944100000001,
 0.33999999999999997,
 -1.4549999999999998,
 1.45,
 0,
 -0.024999999999999967,
 -3.87,
 0.7338461540000001,
 0,
 0.374254658,
 0.6957453419999999,
 0,
 0.186333333,
 -0.29433333300000003,
 0,
 0,
 1.5249999999999995,
 -1.1999999999999993,
 1.5273619629999997,
 -0.7873619630000004,
 1.6749999999999998,
 -1.6899999999999995,
 2.905,
 1.83,
 0,
 0,
 -2.175,
 3.8699999999999997,
 1.9700000000000002,
 -2.3800000000000003,
 -0.9300000000000002,
 0.23500000000000032,
 2.355,
 2.29,
 -0.495,
 0,
 -0.042719836000000004,
 -1.710613497,
 2.206,
 -2.544333333,
 -0.421321839,
 0,
 0,
 -0.273333333,
 -0.42833333300000004,
 0.32333333300000006,
 0.645,
 0,
 0.06,
 0.24,
 -0.27,
 0,
 -0.018000000000000002,
 -0.10200000000000001,
 0,
 -0.034999999999999996,
 0.485,
 0,
 -0.36,
 0.306666667,
 0,
 0,
 4.52,
 0,
 -1.065,
 0,
 0.743333333,
 0.5833333329999999,
 -1.0166666659999999,
 0.754327122,
 0.482339544,
 -0.23,
 -0.14999999999999997,
 0,
 1.636666667,
 0,
 0,
 0.03018633500000001,
 0,
 -0.587666667,
 0.513589744,
 0,
 -0.6549999999999999,
 -0.6784049080000001,
 2.478404908,
 -0.19499999999999995,
 0.275,
 -0.737857143,
 0,
 2.58,
 0.5300000000000002,
 3.0,
 -2.2300000000000004,
 0.9950000000000001,
 1.145,
 3.01,
 -1.75,
 0.020000000000000004,
 -0.013500000000000012,
 0.4885,
 -0.86,
 0.683928571,
 0,
 0.505,
 0,
 0,
 -0.196666666,
 0,
 0.67,
 -3.285,
 0.36499999999999977,
 2.85,
 0.015000000000000013,
 1.4649999999999999,
 -0.6699999999999999,
 -0.30999999999999994,
 0,
 -0.64,
 0,
 0.45,
 -0.445,
 0.185,
 0.101666667,
 0,
 -0.24,
 0,
 -1.8149999999999997,
 -0.7200000000000002,
 2.2800000000000002,
 -2.37,
 1.8549999999999998,
 0.42000000000000015,
 0.695,
 1.65,
 -3.08,
 3.143,
 0,
 -1.3116666659999998,
 0.446666666,
 0.025408997999999988,
 0,
 0,
 3.659,
 -3.836428571,
 0,
 -0.385010225,
 -0.436656442,
 -0.654,
 1.415666667,
 0,
 2.775,
 -1.8050000000000002,
 0.6800000000000002,
 1.055,
 -1.305,
 0.0434482759999999,
 0,
 0,
 -2.37,
 0.06000000000000005,
 0.99,
 0.895,
 0.020000000000000018,
 0.73,
 -1.275,
 1.13,
 0.16499999999999998,
 0.015000000000000013,
 0,
 -0.21950000000000003,
 -1.792,
 0,
 0.193928571,
 0,
 -3.9436666669999996,
 0,
 0,
 -0.0050000000000000044,
 0.03999999999999998,
 -0.7849999999999999,
 1.0350000000000001,
 0,
 -4.8149999999999995,
 2.245,
 1.6949999999999998,
 -1.095,
 2.196521739,
 -1.021521739,
 -0.8749999999999999,
 1.1099999999999999,
 0.13166666700000001,
 -0.9149999999999998,
 0.44583333299999994,
 0.4174999999999999,
 0,
 -0.211666667,
 0.49,
 0,
 -2.5149999999999997,
 -3.79,
 -0.4949999999999992,
 5.3629999999999995,
 0.972,
 -2.9234482760000002,
 0,
 0.13333333399999997,
 -0.8666666670000001,
 0.6466666670000001,
 -0.13666666700000002,
 0,
 -0.010000000000000009,
 0,
 0.103333334,
 -0.883333334,
 -1.4733333329999998,
 1.636666667,
 0.456666666,
 0.09666666699999998,
 0.48333333300000003,
 0,
 -0.2866666669999999,
 -2.0946830260000002,
 -0.24865030700000013,
 4.066666667,
 -3.2933333339999997,
 1.8283333339999999,
 1.448333333,
 -2.787,
 0.4386666670000001,
 2.436190476,
 0,
 -0.558486707,
 -0.706666667,
 -0.6399999999999999,
 0.8033333329999999,
 1.046666667,
 -0.92,
 0.15478260899999996,
 -1.7377826090000001,
 2.966333333,
 0.11809523800000005,
 0,
 -0.41000000000000003,
 -0.10984472,
 0,
 0,
 -0.76,
 1.025,
 -0.9550000000000001,
 -1.5945,
 2.2545,
 2.241,
 0,
 0,
 1.9649999999999999,
 0.08499999999999996,
 0.72,
 1.17,
 -0.465,
 0,
 -7.465,
 1.2749999999999995,
 1.3900000000000006,
 -1.46,
 3.0649999999999995,
 1.81,
 1.125,
 -1.9049999999999998,
 0.7666666669999999,
 0.5123333330000001,
 0,
 -0.17,
 0,
 0,
 0.45166666699999997,
 0,
 -0.3065,
 0.26823913,
 -0.11173912999999999,
 -0.197931034,
 0,
 1.80862069,
 0,
 -1.463333333,
 0,
 0.64,
 0.04999999999999999,
 0,
 0.861293996,
 -1.083666667,
 0.15533333300000002,
 0,
 0,
 -0.03,
 -0.396666667,
 -0.8816666660000001,
 0,
 -1.43,
 1.285,
 -0.16,
 0.19,
 0.005000000000000001,
 0.135,
 0.495,
 -0.62984472,
 -0.32015528,
 0,
 1.565,
 0.558333333,
 -0.769655172,
 -0.13201149499999998,
 0,
 4.975,
 -6.03,
 2.5700000000000003,
 0.9403374229999999,
 0.564662577,
 1.05,
 0,
 0.06500000000000039,
 1.6449999999999996,
 2.06,
 -2.52,
 3.965,
 0,
 0.865,
 0.5916666660000001,
 0,
 -1.6464212679999999,
 1.811421268,
 0.086666666,
 0,
 -0.538128834,
 -2.171871166,
 -2.8035,
 3.1985,
 3.9234482760000002,
 0,
 -1.803333333,
 -1.460897436,
 0,
 1.115,
 -1.5533333329999999,
 0,
 -0.33,
 -1.199461698,
 0.006708074000000064,
 1.182753624,
 -0.5966666669999999,
 1.39,
 0,
 0.173333333,
 0,
 -2.5366666670000004,
 1.1083333340000001,
 1.955,
 -0.36166666700000005,
 -2.493333333,
 1.880296523,
 1.46303681,
 0.538,
 -2.511333333,
 0.3847619040000001,
 0,
 0.980333333,
 0.663,
 -0.661666667,
 0,
 -0.011190476000000005,
 0,
 0.8849999999999998,
 1.6649999999999996,
 -0.27,
 -0.7999999999999998,
 2.795,
 2.235,
 -1.64,
 0,
 -0.525,
 -0.325,
 0.345,
 -1.27,
 1.856666667,
 0.0,
 0.5533333330000001,
 0,
 -0.31000000000000005,
 0.02499999999999991,
 1.085,
 0.42000000000000004,
 0,
 -1.9900000000000002,
 2.453333333,
 -0.8177505109999998,
 2.371083845,
 -0.613333334,
 0.307163561,
 0.079503106,
 0,
 0,
 -1.2149999999999999,
 0,
 1.2200000000000002,
 -2.025,
 1.715,
 -1.115,
 2.98,
 0,
 -1.973333334,
 2.71,
 -0.49000000000000005,
 0.306666667,
 0,
 0.31000000000000005,
 0,
 0.298333334,
 -0.356666667,
 0,
 0,
 0.44499999999999995,
 -0.97,
 0,
 -1.043333333,
 -0.14000000000000007,
 -0.13333333399999991,
 -1.3266666660000002,
 1.6120910970000002,
 2.204575569,
 0,
 -0.3405,
 0,
 0.07999999999999999,
 0,
 0,
 0,
 -2.36,
 0.02499999999999991,
 -0.27,
 3.08,
 0.405,
 -0.040000000000000036,
 0,
 -0.7899999999999999,
 0.82,
 -0.816932515,
 0.050265848,
 0,
 0,
 -1.13,
 -1.7449999999999999,
 2.2824999999999998,
 -1.9674999999999998,
 2.864285714,
 0,
 -1.9916666669999998,
 -0.5866666660000002,
 -0.23266666699999994,
 1.686,
 -0.47640000000000005,
 0,
 -0.16,
 0,
 0,
 0.746,
 0,
 -0.6958695650000002,
 -0.6841304349999997,
 0.09499999999999975,
 2.665,
 -2.25,
 2.9,
 -0.075,
 0,
 0,
 0,
 1.0,
 -0.7616666670000001,
 0,
 1.9243333329999999,
 0,
 -2.3,
 2.515,
 -1.6400000000000001,
 0.3049999999999997,
 -2.9299999999999997,
 1.3049999999999997,
 3.4350000000000005,
 0.5189999999999999,
 0.026000000000000023,
 0,
 0.14500000000000002,
 -0.175,
 -1.395,
 1.8050000000000002,
 0.25666666699999996,
 0,
 2.177,
 -6.122857143,
 0,
 -0.433333334,
 -0.10333333300000003,
 0,
 0.273333333,
 -0.440229885,
 0,
 4.265000000000001,
 0.050000000000000044,
 1.525,
 0,
 0.57,
 0.29000000000000004,
 -0.861666666,
 0.971666666,
 0,
 1.186666667,
 1.06,
 -0.53,
 0.35666666599999997,
 0.21000000000000002,
 -0.636666666,
 0.116666666,
 0,
 0.363333333,
 -0.7211904760000001,
 0,
 -1.3649999999999998,
 -2.87,
 3.13,
 2.438,
 -2.7630000000000003,
 -2.0321999999999996,
 0,
 0,
 -0.14500000000000002,
 -0.275,
 0.45,
 0,
 0.0,
 0,
 -0.656666667,
 0.13999999999999999,
 -3.08,
 1.2516666669999998,
 2.395,
 -0.46499999999999997,
 0.187494824,
 ...]

In [12]:
injury_war_df["WAR_difference"] = war_difference_list
injury_war_df

,player_name,age,key_bbref,year_ID,team_ID,stint_ID,lg_ID,is_P,franch_ID,sched,...,Team,Name,injury_length,Injury,location,days_injured,year,shortname,WAR_change,WAR_difference
54,A.J. Achter,25.0,achteaj01,2014,MIN,1,AL,Y,MIN,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0.000000
55,A.J. Achter,26.0,achteaj01,2015,MIN,1,AL,Y,MIN,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0.116667
56,A.J. Achter,27.0,achteaj01,2016,LAA,1,AL,Y,ANA,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,-0.386667
262,A.J. Alexy,23.0,alexyaj01,2021,TEX,1,AL,Y,TEX,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0.000000
2232,A.J. Burnett,33.0,burnea.01,2010,NYY,1,AL,Y,NYY,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16067,Zeke Spruill,23.0,spruize01,2013,ARI,1,NL,Y,ARI,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0.000000
16068,Zeke Spruill,24.0,spruize01,2014,ARI,1,NL,Y,ARI,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,-0.523333
18010,Zelous Wheeler,27.0,wheelze01,2014,NYY,1,AL,N,NYY,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0.000000
333,Zoilo Almonte,24.0,almonzo01,2013,NYY,1,AL,N,NYY,162,...,Yankees,Zoilo Almonte,15-day,sprained ankle,left,51.0,2013.0,zalmonte,,0.000000
334,Zoilo Almonte,25.0,almonzo01,2014,NYY,1,AL,N,NYY,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,-0.025000

In [13]:
injury_war_df["WAR_change"] = np.where(injury_war_df["WAR_difference"] > 0, 1, 0)
injury_war_df

,player_name,age,key_bbref,year_ID,team_ID,stint_ID,lg_ID,is_P,franch_ID,sched,...,Team,Name,injury_length,Injury,location,days_injured,year,shortname,WAR_change,WAR_difference
54,A.J. Achter,25.0,achteaj01,2014,MIN,1,AL,Y,MIN,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.000000
55,A.J. Achter,26.0,achteaj01,2015,MIN,1,AL,Y,MIN,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0.116667
56,A.J. Achter,27.0,achteaj01,2016,LAA,1,AL,Y,ANA,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,-0.386667
262,A.J. Alexy,23.0,alexyaj01,2021,TEX,1,AL,Y,TEX,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.000000
2232,A.J. Burnett,33.0,burnea.01,2010,NYY,1,AL,Y,NYY,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16067,Zeke Spruill,23.0,spruize01,2013,ARI,1,NL,Y,ARI,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.000000
16068,Zeke Spruill,24.0,spruize01,2014,ARI,1,NL,Y,ARI,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,-0.523333
18010,Zelous Wheeler,27.0,wheelze01,2014,NYY,1,AL,N,NYY,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.000000
333,Zoilo Almonte,24.0,almonzo01,2013,NYY,1,AL,N,NYY,162,...,Yankees,Zoilo Almonte,15-day,sprained ankle,left,51.0,2013.0,zalmonte,0,0.000000
334,Zoilo Almonte,25.0,almonzo01,2014,NYY,1,AL,N,NYY,162,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,-0.025000